[package]
name = "bv"
version = "0.2.8"
edition = "2021"

[dependencies]
askama = { version = "^0", features = ["serde-json", "serde-yaml", "with-axum", "markdown", "mime"] }
axum = { version = "0.8.1", features = ["http2", "ws", "multipart", "macros"] }
envconfig = "0.11.0"
log = "0.4.26"
opendal = { version = "0.54.0", features = ["layers-throttle", "services-s3"] }
serde = { version = "1.0.219", features = ["derive", "rc"] }
bv_templates = { version = "0.1.1", path = "../bv_templates" }
tokio = { version = "1.44.1", features = ["full"] }
tower = { version = "0.5.2", features = ["buffer", "slab", "timeout", "tokio", "tracing", "util"] }
tower-http = { version = "0.6.2", features = ["fs", "trace"] }
tracing = { version = "0.1.41", features = ["async-await", "log"] }
tracing-subscriber = { version = "0.3.19", features = ["serde", "chrono", "env-filter", "once_cell", "serde_json"] }
mime_guess = "2.0.5"
futures = "0.3.31"
base64 = "0.22.1"
once_cell = "1.21.3"
arc-swap = "1.7.1"
prefix-range = "0.1.0"
rustls-platform-verifier = "0.5.1"
reqwest = "0.12.15"
